### ISSUE TITLE
Edit admin organizations controller

### ISSUE THREAD

**Issue by chen-jenn** [chen-jenn/devSpotlight#29]
-add missing code for actions 
-fix associated view pages (admin/views/organizations)

**Comment by chen-jenn** [comment]
i am working on this

**Comment by tylersuzukinelson** [comment]
@chen-jenn Note, you can show you're working on an issue by using the "Assignees" list in the right-hand menu. Similar to pull requests :)

https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
