### ISSUE TITLE
Add additional paths for admin navbar

### ISSUE THREAD

**Issue by chen-jenn** [chen-jenn/devSpotlight#32]
-add the announcements link
-add events link 
-add users link

**Comment by chen-jenn** [comment]
i am doing this

**Comment by tylersuzukinelson** [comment]
@chen-jenn Note, you can show you're working on an issue by using the "Assignees" list in the right-hand menu. Similar to pull requests :)

https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
