### ISSUE TITLE
Problem requiring the gem of the news API

### ISSUE THREAD

**Issue by cedricchou** [chen-jenn/devSpotlight#35]
Rails is throwing me an error when I require 'news-api'

**Comment by soongding87** [comment]
Cedric and Danny working on

**Comment by cedricchou** [comment]
Fixed but still working on making it look good

**Comment by tylersuzukinelson** [comment]
@soongding87 @cedricchou Note, you can show you're working on an issue by using the "Assignees" list in the right-hand menu. Similar to pull requests :)

https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
